### ISSUE TITLE
8.1 の oldest を用意する

### ISSUE THREAD

**Issue by tyru** [vim-jp/redirects#10]
現状
http://vim-jp.org/redirects/koron/vim-kaoriya/vim80/oldest/win64/
はありますが、
http://vim-jp.org/redirects/koron/vim-kaoriya/vim81/oldest/win64/
はまだ用意されていません。

バージョンはいくつが良いでしょうか？
8.1 で深刻なバグ (?) がない比較的安定した一番最初のバージョンにしたいですが…

**Comment by k-takata** [comment]
8.1.0001 がいいんじゃないでしょうか。
パッチ無しの 8.1 は Netrw が動かない不具合があります。

**Comment by k-takata** [comment]
あ、Kaoriya版だと、8.1.0000 と 8.1.0005 しかリリースされてないので、どちらかを選ぶしかないですね。

**Comment by tyru** [comment]
ありがとうございます！~~追加して~~ PR 出してみました！ #11
紛らわしい書き方申し訳ないです…

**Comment by tyru** [comment]
ありがとうございます！
