### ISSUE TITLE
cron の実行を CI サービスに移行する

### ISSUE THREAD

**Issue by thinca** [vim-jp/redirects#16]
現在 cron の実行は koron さんの個人所有のマシンで実行されており、属人性が高くトラブル時に対応が難しい。
幸いやっていることはそこまで難しくはないので、CI サービスの cron 機能を使って cron 処理を実行するようにする。

最有力候補: GitHub Actions  (GitHub のリポジトリへの push アクセスの設定が比較的簡単、のはず、たぶん。)
次点: Travis-CI, CircleCI

**Comment by tsuyoshicho** [comment]
やってる内容がREADMEのものなら、そう難しくはないはずですね...

**Comment by 0Delta** [comment]
作ってPRを作りました。
挙動大丈夫かレビューお願いできれば幸いです…！

**Comment by 0Delta** [comment]
手元で実行した時のログはこちらです。

https://github.com/0Delta/redirects/actions/runs/38006418
 → https://github.com/0Delta/redirects/commit/24cb909783a0f8ce5b7f498fbd31a84246fb4a31

**Comment by 0Delta** [comment]
主な変更点として、`JST` が出力できなかったので時間が `UTC` になってます。
コミットに併記してあるので、 ~早とちりしなければ~ 大丈夫なハズです。

**Comment by thinca** [comment]
#17 #18 で対応されました。 @0Delta ありがとうございました！
