### ISSUE TITLE
Vim 7.3 +kaoriya のバイナリを適切な場所に移す

### ISSUE THREAD

**Issue by koron** [vim-jp/redirects#2]
今は files.kaoriya.net を参照しているが、これは一時的な措置。
どこか cloud に置いて、そちらを参照するようにする。

**Comment by h-east** [comment]
7.3?

**Comment by koron** [comment]
@h-east 詳しくは thinca/vim-themis#31 を参照してほしいのですが、
自動テストの対象として 7.3 を使ってるんです。

で、テストが走るたびに files.kaoriya.net から DL しているのを、
継続性の観点からクライドの別の場所に移したいという状況になっています。

**Comment by koron** [comment]
https://github.com/koron/vim-kaoriya/releases/tag/v7.3-legacy にコピーを用意し、そちらにリンクするようにしました。
