### ISSUE TITLE
jekyll-redirect-from の不具合

### ISSUE THREAD

**Issue by hattya** [vim-jp/redirects#5]
GitHub Pages の Jekyll が 3.1 に更新されてからだと思いますが、リダイレクトページが空になっていて機能していません。

ref: https://github.com/blog/2172-github-pages-now-runs-jekyll-3-1

**Comment by koron** [comment]
thx 確認します。

**Comment by koron** [comment]
1つのソースファイルから `index` と `index.html` の2つが生成されてて、
index には中身が入ってるけど、index.html には入ってない…なんだこりゃ?

**Comment by koron** [comment]
https://github.com/jekyll/jekyll-redirect-from/issues/107 redirect_to appears not to work

これやな…

**Comment by koron** [comment]
- jekyll-redirect-from は `redirect_to` を使ってる `Jekyll::Page` オブジェクト(not `Jekyll::Document`) に対して `RedirectPage` を 追加することで対応している
- `RedirectPage` は `Jekyll::Page` を継承している
- jekyll v3.0.5 の `Jekyll::Page` の `destination` メソッドは、 `/` で終わるURLに対して、 `index.html` というファイルを出力していた
- jekyll v3.1.6 の `Jekyll::Page` の `destination` メソッドは、 `/` で終わるURLに対して `index` + `extname` という方法でファイル名を決めるように変更されている
- `extname` はコンストラクタの第4引数(`name`) で決まってしまう
- `RedirectPage` のコンストラクタの第4引数には `File.dirname(item.url)` が渡されており、これには拡張子が含まれていない
- そのため `destination` は拡張子を含まないファイル名を返す
- 結果、index.html と index という2つのファイルが生成されている

**Comment by koron** [comment]
さて jekyll-redirect-from に修正を PR するにしても、それが github-pages に反映されるにはかなりの時間を要すると考えられる。なので迂回策を本プロジェクトに閉じて実施したほうが良いだろう。

layoutをでっち上げれば、それで良いか。

**Comment by koron** [comment]
e2da8f2 で修正しました。
1. redirect layout を追加
2. `redirect_to` のあるページに `layout: redirect` を追加
3. jekyll-redirect-from` を無効化

**Comment by koron** [comment]
@hattya 私の確認では直ったように観測できました。なので閉じます。

報告をありがとうございました! :bow: & :cake:

**Comment by koron** [comment]
cronが悪さして、再発中。

**Comment by koron** [comment]
とりあえず cron 実行環境で更新用プログラム(vim_jp-redirects-update)を更新し、強制実行することで対応した。

vim_jp-redirects-update の取り扱いについては要改善。
