### ISSUE TITLE
cronでvim_jp-redirects-updateを最新に更新する

### ISSUE THREAD

**Issue by koron** [vim-jp/redirects#6]
現在cronでは vim_jp-redirects-update がPATH内にインストール済みならそれを使って更新している。
そのため vim_jp-redirects-update のソースが更新された際にそれが反映されず、
#5 の問題を再発させた。

これをソースが更新されていたら vim_jp-redirects-update をリビルドして使うように
cron関係のスクリプトを変更する。

**Comment by k-takata** [comment]
#17 がマージされたので閉じちゃいます。
